---
title: "p8105_hw6_rd3096"
author: Timothy Du
output: github_document
---

# load necessary pakages 
```{r setup}
library(tidyverse)
library(rnoaa)
library(ggplot2)
library(modelr)
library(mgcv)
library(broom)

set.seed(1)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## problem 1
we need to download the dataset using the code chunk below
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

str(weather_df)
```

Next, we will perform bootstrap sampling and regression analysis.

First, we need to write a function to create the two quantities that we are interested.
```{r}
compute_metrics = function(weather_sample) {
  model = lm(tmax ~ tmin, weather_sample)
  r_squared = glance(model)$r.squared
  coefficients = tidy(model)
  intercept = coefficients %>% 
    filter(term == "(Intercept)") %>% 
    pull(estimate)
  
  slope = coefficients %>%
    filter(term == "tmin") %>% 
    pull(estimate)
  
  log_beta_product = log(intercept * slope)
  
  tibble(
    r_squared = r_squared,
    log_beta_product = log_beta_product
  )
}
```

